---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-api-37348950
  labels:
    app: my-spring-api-37348950
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: my-spring-api-37348950
  template:
    metadata:
      labels:
        app: my-spring-api-37348950
    spec:
      serviceAccountName: ingress-manager
      containers:
        - name: my-spring-api-37348950
          image: docker.io/phengbunath/my-spring-api-37348950:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
